import { defineField, defineType } from "sanity";

export const university = defineType({
  name: "university",
  title: "University Master Record",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "University Name",
      type: "string",
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: {
        source: "name",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      options: {
        list: [
          { title: "United States", value: "usa" },
          { title: "United Kingdom", value: "uk" },
          { title: "Canada", value: "canada" },
          { title: "Australia", value: "australia" },
          { title: "Germany", value: "germany" },
          { title: "Ireland", value: "ireland" },
          { title: "New Zealand", value: "new-zealand" },
          { title: "France", value: "france" },
          { title: "Italy", value: "italy" },
          { title: "Netherlands", value: "netherlands" },
          { title: "Singapore", value: "singapore" },
          { title: "Malaysia", value: "malaysia" },
          { title: "United Arab Emirates", value: "uae" },
          { title: "Russia", value: "russia" },
          { title: "Uzbekistan", value: "uzbekistan" },
          { title: "Kazakhstan", value: "kazakhstan" },
          { title: "Kyrgyzstan", value: "kyrgyzstan" },
          { title: "Georgia", value: "georgia" },
          { title: "Philippines", value: "philippines" },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "city",
      title: "City / Campus Location",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "rankingGlobal",
      title: "QS World Ranking",
      type: "number",
      description: "e.g., 28 for TU Munich, 33 for Georgia Tech",
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "rankingNational",
      title: "National Rank in Country",
      type: "number",
      description: "e.g., #1 in Germany",
    }),
    defineField({
      name: "tuitionFeeRangeINR",
      title: "Tuition Fee Range in INR (₹)",
      type: "string",
      description: "e.g., ₹0 (Free / Semester Ticket Only) or ₹25 - 40 Lakhs / yr",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ieltsMinScore",
      title: "Minimum IELTS Band Score",
      type: "number",
      description: "e.g., 6.5 or 7.0",
      initialValue: 6.5,
    }),
    defineField({
      name: "greGmatRequired",
      title: "GRE / GMAT Required?",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "acceptanceRate",
      title: "Acceptance Rate (%)",
      type: "number",
      description: "e.g., 8 for 8%",
    }),
    defineField({
      name: "postStudyWorkMonths",
      title: "Post-Study Work Visa (Months)",
      type: "number",
      description: "e.g., 18 for Germany, 36 for US STEM OPT",
      initialValue: 24,
    }),
    defineField({
      name: "featured",
      title: "Featured on Homepage?",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "logo",
      title: "University Crest / Logo",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "banner",
      title: "Campus Cover Banner Photo",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "overview",
      title: "University Overview & Admissions Guide",
      type: "text",
      rows: 4,
      description: "Comprehensive summary of campus labs, faculty strength, and Indian student intake tips.",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "tuitionFeeRangeINR",
      media: "logo",
    },
  },
});
