-- StudyAbroad Vista: Master University Catalog Seeding (All 18 Global Universities)
-- Run this script in your Supabase SQL Editor to populate all 18 institutions across 19 destinations.

-- Ensure schema column compatibility
ALTER TABLE IF EXISTS universities ADD COLUMN IF NOT EXISTS official_email_address VARCHAR(128);
ALTER TABLE IF EXISTS universities ADD COLUMN IF NOT EXISTS official_email_domain VARCHAR(128);

INSERT INTO universities (
    name,
    slug,
    country_id,
    city,
    ranking_global,
    ranking_national,
    programs_offered,
    tuition_fee_range_inr,
    ielts_min_score,
    gre_gmat_required,
    intakes,
    acceptance_rate,
    post_study_work_months,
    featured,
    official_email_address,
    official_email_domain,
    claimed_status
) VALUES
-- 1. Germany - TUM
(
    'Technical University of Munich (TUM)',
    'technical-university-of-munich',
    'germany',
    'Munich',
    28,
    1,
    ARRAY['ms'::program_category, 'bachelors'::program_category],
    '₹0 (Free / Semester ticket only)',
    6.5,
    FALSE,
    ARRAY['Winter (October)', 'Summer (April)'],
    8,
    18,
    TRUE,
    'admissions@tum.de',
    'tum.de',
    'unclaimed'
),
-- 2. USA - Georgia Tech
(
    'Georgia Institute of Technology',
    'georgia-tech',
    'usa',
    'Atlanta, GA',
    33,
    8,
    ARRAY['ms'::program_category, 'bachelors'::program_category],
    '₹28 - 38 Lakhs / yr',
    7.0,
    TRUE,
    ARRAY['Fall (August)', 'Spring (January)'],
    16,
    36,
    TRUE,
    'admissions@gatech.edu',
    'gatech.edu',
    'unclaimed'
),
-- 3. UK - Oxford
(
    'University of Oxford',
    'university-of-oxford',
    'uk',
    'Oxford',
    4,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'phd'::program_category],
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category],
    '₹30 - 42 Lakhs / yr',
    7.5,
    FALSE,
    ARRAY['October'],
    17,
    24,
    TRUE,
    'admissions@ox.ac.uk',
    'ox.ac.uk',
    'unclaimed'
),
-- 4. USA - Stanford
(
    'Stanford University',
    'stanford-university',
    'usa',
    'Stanford, CA',
    3,
    2,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'phd'::program_category],
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category],
    '₹45 - 58 Lakhs / yr',
    7.5,
    TRUE,
    ARRAY['Fall (September)'],
    4,
    36,
    TRUE,
    'admissions@stanford.edu',
    'stanford.edu',
    'unclaimed'
),
-- 5. UK - Manchester
(
    'University of Manchester',
    'university-of-manchester',
    'uk',
    'Manchester',
    32,
    6,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'nursing'::program_category],
    '₹24 - 34 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    27,
    24,
    TRUE,
    'admissions@manchester.ac.uk',
    'manchester.ac.uk',
    'unclaimed'
),
-- 6. Ireland - Trinity College Dublin
(
    'Trinity College Dublin',
    'trinity-college-dublin',
    'ireland',
    'Dublin',
    81,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'nursing'::program_category],
    '₹18 - 26 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    33,
    24,
    TRUE,
    'admissions@tcd.ie',
    'tcd.ie',
    'unclaimed'
),
-- 7. Australia - University of Melbourne
(
    'University of Melbourne',
    'university-of-melbourne',
    'australia',
    'Melbourne',
    14,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'nursing'::program_category],
    '₹26 - 40 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['February', 'July'],
    40,
    36,
    TRUE,
    'admissions@unimelb.edu.au',
    'unimelb.edu.au',
    'unclaimed'
),
-- 8. Uzbekistan - Tashkent Medical Academy
(
    'Tashkent Medical Academy',
    'tashkent-medical-academy',
    'uzbekistan',
    'Tashkent',
    450,
    1,
    ARRAY['mbbs'::program_category],
    '₹3.2 Lakhs / yr',
    5.5,
    FALSE,
    ARRAY['September', 'February'],
    65,
    12,
    TRUE,
    'admissions@tma.uz',
    'tma.uz',
    'unclaimed'
),
-- 9. Canada - University of Toronto
(
    'University of Toronto',
    'university-of-toronto',
    'canada',
    'Toronto',
    21,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'nursing'::program_category],
    '₹22 - 38 Lakhs / yr',
    7.0,
    FALSE,
    ARRAY['Fall (September)'],
    43,
    36,
    TRUE,
    'admissions@utoronto.ca',
    'utoronto.ca',
    'unclaimed'
),
-- 10. France - Sorbonne University
(
    'Sorbonne University',
    'sorbonne-university',
    'france',
    'Paris',
    59,
    2,
    ARRAY['ms'::program_category, 'bachelors'::program_category, 'phd'::program_category],
    ARRAY['ms'::program_category, 'bachelors'::program_category],
    '₹2.5 - 6.5 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September', 'January'],
    15,
    24,
    TRUE,
    'admissions@sorbonne-universite.fr',
    'sorbonne-universite.fr',
    'unclaimed'
),
-- 11. France - HEC Paris
(
    'HEC Paris',
    'hec-paris',
    'france',
    'Jouy-en-Josas, Paris',
    10,
    1,
    ARRAY['mba'::program_category, 'ms'::program_category, 'bachelors'::program_category, 'emba'::program_category],
    ARRAY['mba'::program_category, 'ms'::program_category, 'bachelors'::program_category],
    '₹22 - 38 Lakhs / yr',
    7.0,
    TRUE,
    ARRAY['September', 'January'],
    8,
    24,
    TRUE,
    'admissions@hec.fr',
    'hec.fr',
    'unclaimed'
),
-- 12. France - École Polytechnique
(
    'École Polytechnique',
    'polytechnique-paris',
    'france',
    'Palaiseau, Paris',
    38,
    2,
    ARRAY['bachelors'::program_category, 'ms'::program_category, 'phd'::program_category],
    ARRAY['bachelors'::program_category, 'ms'::program_category],
    '₹12 - 19 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    10,
    24,
    TRUE,
    'admissions@polytechnique.edu',
    'polytechnique.edu',
    'unclaimed'
),
-- 13. France - ESSEC Business School
(
    'ESSEC Business School',
    'essec-business-school',
    'france',
    'Cergy, Paris',
    15,
    2,
    ARRAY['bachelors'::program_category, 'ms'::program_category, 'mba'::program_category],
    '₹16 - 28 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    18,
    24,
    TRUE,
    'admissions@essec.edu',
    'essec.edu',
    'unclaimed'
),
-- 14. France - PSL University
(
    'PSL University (Université PSL)',
    'psl-university',
    'france',
    'Paris',
    24,
    1,
    ARRAY['bachelors'::program_category, 'ms'::program_category, 'phd'::program_category],
    ARRAY['bachelors'::program_category, 'ms'::program_category],
    '₹3.0 - 8.5 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    12,
    24,
    TRUE,
    'admissions@psl.eu',
    'psl.eu',
    'unclaimed'
),
-- 15. Netherlands - TU Delft
(
    'Delft University of Technology (TU Delft)',
    'tu-delft',
    'netherlands',
    'Delft',
    47,
    1,
    ARRAY['ms'::program_category, 'bachelors'::program_category, 'phd'::program_category],
    ARRAY['ms'::program_category, 'bachelors'::program_category],
    '₹14 - 22 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['September'],
    20,
    12,
    TRUE,
    'admissions@tudelft.nl',
    'tudelft.nl',
    'unclaimed'
),
-- 16. Italy - Sapienza University of Rome
(
    'Sapienza University of Rome',
    'sapienza-university-of-rome',
    'italy',
    'Rome',
    134,
    1,
    ARRAY['ms'::program_category, 'bachelors'::program_category, 'mbbs'::program_category],
    '₹1.5 - 4.5 Lakhs / yr',
    6.0,
    FALSE,
    ARRAY['September'],
    35,
    12,
    TRUE,
    'admissions@uniroma1.it',
    'uniroma1.it',
    'unclaimed'
),
-- 17. Singapore - NUS
(
    'National University of Singapore (NUS)',
    'national-university-of-singapore',
    'singapore',
    'Singapore',
    8,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'phd'::program_category],
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category],
    '₹20 - 35 Lakhs / yr',
    6.5,
    TRUE,
    ARRAY['August', 'January'],
    7,
    24,
    TRUE,
    'admissions@nus.edu.sg',
    'nus.edu.sg',
    'unclaimed'
),
-- 18. New Zealand - University of Auckland
(
    'University of Auckland',
    'university-of-auckland',
    'new-zealand',
    'Auckland',
    68,
    1,
    ARRAY['ms'::program_category, 'mba'::program_category, 'bachelors'::program_category, 'nursing'::program_category],
    '₹18 - 30 Lakhs / yr',
    6.5,
    FALSE,
    ARRAY['February', 'July'],
    45,
    36,
    TRUE,
    'admissions@auckland.ac.nz',
    'auckland.ac.nz',
    'unclaimed'
)
ON CONFLICT (slug) DO UPDATE SET
    official_email_address = EXCLUDED.official_email_address,
    official_email_domain = EXCLUDED.official_email_domain,
    ranking_global = EXCLUDED.ranking_global,
    ranking_national = EXCLUDED.ranking_national,
    tuition_fee_range_inr = EXCLUDED.tuition_fee_range_inr,
    intakes = EXCLUDED.intakes,
    post_study_work_months = EXCLUDED.post_study_work_months,
    featured = EXCLUDED.featured;

